### ISSUE TITLE
Electron JS v7 Breaks Dashboard

### ISSUE THREAD

**Issue by willswire** [willswire/balena-dashboards#7]
It works, thanks a lot!
But, there is another issue with Electron itself, which is not going to be appropriately installed (i use RPi2).
This issue [#21070](https://github.com/electron/electron/issues/21070) was already reported.

Here is the error from the build log:
```
[electron]    > electron@7.1.1 postinstall /usr/src/app/node_modules/electron
[electron]    > node install.js
[electron]    (node:38) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
[electron]        at EventEmitter.<anonymous> (/usr/src/app/node_modules/got/source/as-stream.js:35:24)
[electron]        at EventEmitter.emit (events.js:210:5)
[electron]        at module.exports (/usr/src/app/node_modules/got/source/get-response.js:22:10)
[electron]        at ClientRequest.handleResponse (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:155:5)
[electron]        at Object.onceWrapper (events.js:300:26)
[electron]        at ClientRequest.emit (events.js:215:7)
[electron]        at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
[electron]        at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:585:27)
[electron]        at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
[electron]        at TLSSocket.socketOnData (_http_client.js:454:22)
[electron]    (node:38) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[electron]    (node:38) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[
```
When it's downgraded to version 6.1.4, everything seems to be okay:
```
root@6f838e3:/usr/src/app# npm install electron@6

> electron@6.1.4 postinstall /usr/src/app/node_modules/electron
> node install.js

Downloading tmp-85-1-SHASUMS256.txt-6.1.4
[============================================>] 100.0% of 5.15 kB (5.15 kB/s)
+ electron@6.1.4
added 112 packages from 96 contributors, removed 51 packages, updated 14 packages and audited 204 packages in 101.151s
found 0 vulnerabilities



   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New minor version of npm available! 6.12.0 → 6.13.0       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.13.0   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

root@6f838e3:/usr/src/app# ./start.sh &
[1] 96
Setting hostname...
Increased memory allocation
Removed temporary startx data
$NOVNC_PASSWORD is set
Storing X11 VNC password...
mkdir: cannot create directory ‘/root/.x11vnc’: File exists
stored passwd in file: /root/.x11vnc/passwd
Setup complete

The VNC desktop is:      6f838e3:1
PORT=5901


X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.15.0-48-generic armv8l Raspbian
Current Operating System: Linux 6f838e3 4.19.71 #1 SMP Tue Sep 17 09:52:03 UTC 2019 armv7l
Kernel command line: coherent_pool=1M bcm2708_fb.fbwidth=1920 bcm2708_fb.fbheight=1200 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=null rootfstype=ext4 rootwait vt.global_cursor_default=0 root=PARTUUID=4f14f3cf-02 rootwait
Build Date: 05 June 2019  12:49:54PM
xorg-server 2:1.20.4-1+rpt1 (https://www.debian.org/support) 
Current version of pixman: 0.36.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Mon Nov 11 18:31:35 2019
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Starting dashboard...
The screen dimensions are: { width: 1920, height: 1200 }
The display will be kept alive: true
Slides created
Slides configured
```

_Originally posted by @rudam in https://github.com/willswire/balena-dashboards/issues/5#issuecomment-552564422_

**Comment by willswire** [comment]
@rudam once the folks over at electron get this figured out, please let me know.

**Comment by willswire** [comment]
@rudam @roinone - I have a potential fix for this issue and #8, but need some testers with a spare pi handy. Either of you able to test and report back the results?

**Comment by roinone** [comment]
Yes, I am able, although I may not be very timely on testing.

**Comment by willswire** [comment]
@roinone checkout the [dev](https://github.com/willswire/balena-dashboards/tree/dev) branch, which has a fix for this issue. confirmed working on my Raspberry Pi v3B+
